/**
 * countries.ts — Lista abrangente de países com código internacional (DDI) e
 * bandeira, para o <select> de origem do pré-cadastro público.
 *
 * IMPORTANTE: o valor da opção é `${name} (+${ddi})`. O código do formulário
 * detecta brasileiro por `docOrigin === "Brasil (+55)"` (CPF/RG vs passaporte),
 * então a entrada do Brasil precisa manter exatamente nome "Brasil" e ddi "55".
 */
export interface Country {
  name: string; // nome em PT-BR (usado no value → não mudar "Brasil")
  ddi: string;  // código internacional, sem o "+"
  flag: string; // emoji da bandeira
}

// Brasil primeiro (default e mais comum); o restante é ordenado alfabeticamente.
const REST: Country[] = [
  { name: "Afeganistão", ddi: "93", flag: "🇦🇫" },
  { name: "África do Sul", ddi: "27", flag: "🇿🇦" },
  { name: "Albânia", ddi: "355", flag: "🇦🇱" },
  { name: "Alemanha", ddi: "49", flag: "🇩🇪" },
  { name: "Andorra", ddi: "376", flag: "🇦🇩" },
  { name: "Angola", ddi: "244", flag: "🇦🇴" },
  { name: "Antígua e Barbuda", ddi: "1268", flag: "🇦🇬" },
  { name: "Arábia Saudita", ddi: "966", flag: "🇸🇦" },
  { name: "Argélia", ddi: "213", flag: "🇩🇿" },
  { name: "Argentina", ddi: "54", flag: "🇦🇷" },
  { name: "Armênia", ddi: "374", flag: "🇦🇲" },
  { name: "Austrália", ddi: "61", flag: "🇦🇺" },
  { name: "Áustria", ddi: "43", flag: "🇦🇹" },
  { name: "Azerbaijão", ddi: "994", flag: "🇦🇿" },
  { name: "Bahamas", ddi: "1242", flag: "🇧🇸" },
  { name: "Bahrein", ddi: "973", flag: "🇧🇭" },
  { name: "Bangladesh", ddi: "880", flag: "🇧🇩" },
  { name: "Barbados", ddi: "1246", flag: "🇧🇧" },
  { name: "Bélgica", ddi: "32", flag: "🇧🇪" },
  { name: "Belize", ddi: "501", flag: "🇧🇿" },
  { name: "Benin", ddi: "229", flag: "🇧🇯" },
  { name: "Bielorrússia", ddi: "375", flag: "🇧🇾" },
  { name: "Bolívia", ddi: "591", flag: "🇧🇴" },
  { name: "Bósnia e Herzegovina", ddi: "387", flag: "🇧🇦" },
  { name: "Botsuana", ddi: "267", flag: "🇧🇼" },
  { name: "Brunei", ddi: "673", flag: "🇧🇳" },
  { name: "Bulgária", ddi: "359", flag: "🇧🇬" },
  { name: "Burkina Faso", ddi: "226", flag: "🇧🇫" },
  { name: "Burundi", ddi: "257", flag: "🇧🇮" },
  { name: "Butão", ddi: "975", flag: "🇧🇹" },
  { name: "Cabo Verde", ddi: "238", flag: "🇨🇻" },
  { name: "Camarões", ddi: "237", flag: "🇨🇲" },
  { name: "Camboja", ddi: "855", flag: "🇰🇭" },
  { name: "Canadá", ddi: "1", flag: "🇨🇦" },
  { name: "Catar", ddi: "974", flag: "🇶🇦" },
  { name: "Cazaquistão", ddi: "7", flag: "🇰🇿" },
  { name: "Chade", ddi: "235", flag: "🇹🇩" },
  { name: "Chile", ddi: "56", flag: "🇨🇱" },
  { name: "China", ddi: "86", flag: "🇨🇳" },
  { name: "Chipre", ddi: "357", flag: "🇨🇾" },
  { name: "Cingapura", ddi: "65", flag: "🇸🇬" },
  { name: "Colômbia", ddi: "57", flag: "🇨🇴" },
  { name: "Comores", ddi: "269", flag: "🇰🇲" },
  { name: "Congo", ddi: "242", flag: "🇨🇬" },
  { name: "Coreia do Norte", ddi: "850", flag: "🇰🇵" },
  { name: "Coreia do Sul", ddi: "82", flag: "🇰🇷" },
  { name: "Costa do Marfim", ddi: "225", flag: "🇨🇮" },
  { name: "Costa Rica", ddi: "506", flag: "🇨🇷" },
  { name: "Croácia", ddi: "385", flag: "🇭🇷" },
  { name: "Cuba", ddi: "53", flag: "🇨🇺" },
  { name: "Dinamarca", ddi: "45", flag: "🇩🇰" },
  { name: "Djibuti", ddi: "253", flag: "🇩🇯" },
  { name: "Dominica", ddi: "1767", flag: "🇩🇲" },
  { name: "Egito", ddi: "20", flag: "🇪🇬" },
  { name: "El Salvador", ddi: "503", flag: "🇸🇻" },
  { name: "Emirados Árabes Unidos", ddi: "971", flag: "🇦🇪" },
  { name: "Equador", ddi: "593", flag: "🇪🇨" },
  { name: "Eritreia", ddi: "291", flag: "🇪🇷" },
  { name: "Escócia", ddi: "44", flag: "🏴" },
  { name: "Eslováquia", ddi: "421", flag: "🇸🇰" },
  { name: "Eslovênia", ddi: "386", flag: "🇸🇮" },
  { name: "Espanha", ddi: "34", flag: "🇪🇸" },
  { name: "Estados Unidos", ddi: "1", flag: "🇺🇸" },
  { name: "Estônia", ddi: "372", flag: "🇪🇪" },
  { name: "Eswatini", ddi: "268", flag: "🇸🇿" },
  { name: "Etiópia", ddi: "251", flag: "🇪🇹" },
  { name: "Fiji", ddi: "679", flag: "🇫🇯" },
  { name: "Filipinas", ddi: "63", flag: "🇵🇭" },
  { name: "Finlândia", ddi: "358", flag: "🇫🇮" },
  { name: "França", ddi: "33", flag: "🇫🇷" },
  { name: "Gabão", ddi: "241", flag: "🇬🇦" },
  { name: "Gâmbia", ddi: "220", flag: "🇬🇲" },
  { name: "Gana", ddi: "233", flag: "🇬🇭" },
  { name: "Geórgia", ddi: "995", flag: "🇬🇪" },
  { name: "Granada", ddi: "1473", flag: "🇬🇩" },
  { name: "Grécia", ddi: "30", flag: "🇬🇷" },
  { name: "Guatemala", ddi: "502", flag: "🇬🇹" },
  { name: "Guiana", ddi: "592", flag: "🇬🇾" },
  { name: "Guiné", ddi: "224", flag: "🇬🇳" },
  { name: "Guiné-Bissau", ddi: "245", flag: "🇬🇼" },
  { name: "Guiné Equatorial", ddi: "240", flag: "🇬🇶" },
  { name: "Haiti", ddi: "509", flag: "🇭🇹" },
  { name: "Holanda", ddi: "31", flag: "🇳🇱" },
  { name: "Honduras", ddi: "504", flag: "🇭🇳" },
  { name: "Hong Kong", ddi: "852", flag: "🇭🇰" },
  { name: "Hungria", ddi: "36", flag: "🇭🇺" },
  { name: "Iêmen", ddi: "967", flag: "🇾🇪" },
  { name: "Ilhas Marshall", ddi: "692", flag: "🇲🇭" },
  { name: "Ilhas Salomão", ddi: "677", flag: "🇸🇧" },
  { name: "Índia", ddi: "91", flag: "🇮🇳" },
  { name: "Indonésia", ddi: "62", flag: "🇮🇩" },
  { name: "Irã", ddi: "98", flag: "🇮🇷" },
  { name: "Iraque", ddi: "964", flag: "🇮🇶" },
  { name: "Irlanda", ddi: "353", flag: "🇮🇪" },
  { name: "Islândia", ddi: "354", flag: "🇮🇸" },
  { name: "Israel", ddi: "972", flag: "🇮🇱" },
  { name: "Itália", ddi: "39", flag: "🇮🇹" },
  { name: "Jamaica", ddi: "1876", flag: "🇯🇲" },
  { name: "Japão", ddi: "81", flag: "🇯🇵" },
  { name: "Jordânia", ddi: "962", flag: "🇯🇴" },
  { name: "Kosovo", ddi: "383", flag: "🇽🇰" },
  { name: "Kuwait", ddi: "965", flag: "🇰🇼" },
  { name: "Laos", ddi: "856", flag: "🇱🇦" },
  { name: "Lesoto", ddi: "266", flag: "🇱🇸" },
  { name: "Letônia", ddi: "371", flag: "🇱🇻" },
  { name: "Líbano", ddi: "961", flag: "🇱🇧" },
  { name: "Libéria", ddi: "231", flag: "🇱🇷" },
  { name: "Líbia", ddi: "218", flag: "🇱🇾" },
  { name: "Liechtenstein", ddi: "423", flag: "🇱🇮" },
  { name: "Lituânia", ddi: "370", flag: "🇱🇹" },
  { name: "Luxemburgo", ddi: "352", flag: "🇱🇺" },
  { name: "Macau", ddi: "853", flag: "🇲🇴" },
  { name: "Macedônia do Norte", ddi: "389", flag: "🇲🇰" },
  { name: "Madagascar", ddi: "261", flag: "🇲🇬" },
  { name: "Malásia", ddi: "60", flag: "🇲🇾" },
  { name: "Malaui", ddi: "265", flag: "🇲🇼" },
  { name: "Maldivas", ddi: "960", flag: "🇲🇻" },
  { name: "Mali", ddi: "223", flag: "🇲🇱" },
  { name: "Malta", ddi: "356", flag: "🇲🇹" },
  { name: "Marrocos", ddi: "212", flag: "🇲🇦" },
  { name: "Maurício", ddi: "230", flag: "🇲🇺" },
  { name: "Mauritânia", ddi: "222", flag: "🇲🇷" },
  { name: "México", ddi: "52", flag: "🇲🇽" },
  { name: "Mianmar", ddi: "95", flag: "🇲🇲" },
  { name: "Micronésia", ddi: "691", flag: "🇫🇲" },
  { name: "Moçambique", ddi: "258", flag: "🇲🇿" },
  { name: "Moldávia", ddi: "373", flag: "🇲🇩" },
  { name: "Mônaco", ddi: "377", flag: "🇲🇨" },
  { name: "Mongólia", ddi: "976", flag: "🇲🇳" },
  { name: "Montenegro", ddi: "382", flag: "🇲🇪" },
  { name: "Namíbia", ddi: "264", flag: "🇳🇦" },
  { name: "Nauru", ddi: "674", flag: "🇳🇷" },
  { name: "Nepal", ddi: "977", flag: "🇳🇵" },
  { name: "Nicarágua", ddi: "505", flag: "🇳🇮" },
  { name: "Níger", ddi: "227", flag: "🇳🇪" },
  { name: "Nigéria", ddi: "234", flag: "🇳🇬" },
  { name: "Noruega", ddi: "47", flag: "🇳🇴" },
  { name: "Nova Zelândia", ddi: "64", flag: "🇳🇿" },
  { name: "Omã", ddi: "968", flag: "🇴🇲" },
  { name: "País de Gales", ddi: "44", flag: "🏴" },
  { name: "Países Baixos", ddi: "31", flag: "🇳🇱" },
  { name: "Palau", ddi: "680", flag: "🇵🇼" },
  { name: "Palestina", ddi: "970", flag: "🇵🇸" },
  { name: "Panamá", ddi: "507", flag: "🇵🇦" },
  { name: "Papua-Nova Guiné", ddi: "675", flag: "🇵🇬" },
  { name: "Paquistão", ddi: "92", flag: "🇵🇰" },
  { name: "Paraguai", ddi: "595", flag: "🇵🇾" },
  { name: "Peru", ddi: "51", flag: "🇵🇪" },
  { name: "Polônia", ddi: "48", flag: "🇵🇱" },
  { name: "Porto Rico", ddi: "1787", flag: "🇵🇷" },
  { name: "Portugal", ddi: "351", flag: "🇵🇹" },
  { name: "Quênia", ddi: "254", flag: "🇰🇪" },
  { name: "Quirguistão", ddi: "996", flag: "🇰🇬" },
  { name: "Reino Unido", ddi: "44", flag: "🇬🇧" },
  { name: "República Centro-Africana", ddi: "236", flag: "🇨🇫" },
  { name: "República Democrática do Congo", ddi: "243", flag: "🇨🇩" },
  { name: "República Dominicana", ddi: "1809", flag: "🇩🇴" },
  { name: "República Tcheca", ddi: "420", flag: "🇨🇿" },
  { name: "Romênia", ddi: "40", flag: "🇷🇴" },
  { name: "Ruanda", ddi: "250", flag: "🇷🇼" },
  { name: "Rússia", ddi: "7", flag: "🇷🇺" },
  { name: "Samoa", ddi: "685", flag: "🇼🇸" },
  { name: "San Marino", ddi: "378", flag: "🇸🇲" },
  { name: "Santa Lúcia", ddi: "1758", flag: "🇱🇨" },
  { name: "São Cristóvão e Névis", ddi: "1869", flag: "🇰🇳" },
  { name: "São Tomé e Príncipe", ddi: "239", flag: "🇸🇹" },
  { name: "São Vicente e Granadinas", ddi: "1784", flag: "🇻🇨" },
  { name: "Senegal", ddi: "221", flag: "🇸🇳" },
  { name: "Serra Leoa", ddi: "232", flag: "🇸🇱" },
  { name: "Sérvia", ddi: "381", flag: "🇷🇸" },
  { name: "Seychelles", ddi: "248", flag: "🇸🇨" },
  { name: "Síria", ddi: "963", flag: "🇸🇾" },
  { name: "Somália", ddi: "252", flag: "🇸🇴" },
  { name: "Sri Lanka", ddi: "94", flag: "🇱🇰" },
  { name: "Sudão", ddi: "249", flag: "🇸🇩" },
  { name: "Sudão do Sul", ddi: "211", flag: "🇸🇸" },
  { name: "Suécia", ddi: "46", flag: "🇸🇪" },
  { name: "Suíça", ddi: "41", flag: "🇨🇭" },
  { name: "Suriname", ddi: "597", flag: "🇸🇷" },
  { name: "Tailândia", ddi: "66", flag: "🇹🇭" },
  { name: "Taiwan", ddi: "886", flag: "🇹🇼" },
  { name: "Tajiquistão", ddi: "992", flag: "🇹🇯" },
  { name: "Tanzânia", ddi: "255", flag: "🇹🇿" },
  { name: "Timor-Leste", ddi: "670", flag: "🇹🇱" },
  { name: "Togo", ddi: "228", flag: "🇹🇬" },
  { name: "Tonga", ddi: "676", flag: "🇹🇴" },
  { name: "Trinidad e Tobago", ddi: "1868", flag: "🇹🇹" },
  { name: "Tunísia", ddi: "216", flag: "🇹🇳" },
  { name: "Turcomenistão", ddi: "993", flag: "🇹🇲" },
  { name: "Turquia", ddi: "90", flag: "🇹🇷" },
  { name: "Tuvalu", ddi: "688", flag: "🇹🇻" },
  { name: "Ucrânia", ddi: "380", flag: "🇺🇦" },
  { name: "Uganda", ddi: "256", flag: "🇺🇬" },
  { name: "Uruguai", ddi: "598", flag: "🇺🇾" },
  { name: "Uzbequistão", ddi: "998", flag: "🇺🇿" },
  { name: "Vanuatu", ddi: "678", flag: "🇻🇺" },
  { name: "Vaticano", ddi: "379", flag: "🇻🇦" },
  { name: "Venezuela", ddi: "58", flag: "🇻🇪" },
  { name: "Vietnã", ddi: "84", flag: "🇻🇳" },
  { name: "Zâmbia", ddi: "260", flag: "🇿🇲" },
  { name: "Zimbábue", ddi: "263", flag: "🇿🇼" },
].sort((a, b) => a.name.localeCompare(b.name, "pt-BR"));

export const COUNTRIES: Country[] = [
  { name: "Brasil", ddi: "55", flag: "🇧🇷" }, // default — não mover (isBrazilian)
  ...REST,
];

/** Valor da opção usado pelo <select> (e persistido em docOrigin). */
export const countryOptionValue = (c: Country) => `${c.name} (+${c.ddi})`;
